import {
  Building2,
  Users,
  Target,
  Rocket,
  QrCode,
  CheckCircle,
  Menu,
  X,
  ChevronRight,
  BookOpen,
  PieChart,
  Briefcase,
  TrendingUp,
  MapPin,
  Phone,
  Mail,
  Calendar,
  Clock,
  ArrowRight,
  MonitorPlay,
  PlayCircle
} from "lucide-react";

export const Icons = {
  Building: Building2,
  Users: Users,
  Target: Target,
  Rocket: Rocket,
  QrCode: QrCode,
  CheckCircle: CheckCircle,
  Menu: Menu,
  Close: X,
  ChevronRight: ChevronRight,
  BookOpen: BookOpen,
  PieChart: PieChart,
  Briefcase: Briefcase,
  TrendingUp: TrendingUp,
  MapPin: MapPin,
  Phone: Phone,
  Mail: Mail,
  Calendar: Calendar,
  Clock: Clock,
  ArrowRight: ArrowRight,
  MonitorPlay: MonitorPlay,
  PlayCircle: PlayCircle
};
